alias vi="nvim"
alias bt="bluetoothctl"
alias fu="sudo pacman -Suy --noconfirm"
alias dot="cd $HOME/.dotfiles ; vi"
alias tmux="tmux -f ~/.dotfiles/tmux/tmux.conf"
alias sc="vi ~/.ssh/config"
alias ls="ls --color=auto"
alias xdg="bash $HOME/.dotfiles/hypr/scripts/xdg-troubleshooting.sh"
